#!/usr/bin/env bash

echo "Generating wrappers for NIDAQmx, please wait. This may take some time."

NIDAQmx_file=$1
OUTPUT_DIR=$2

OUTFILE_TASK_CPP=${OUTPUT_DIR}/NIDAQmx_task_wrapper_methods.cpp
OUTFILE_TASK_H=${OUTPUT_DIR}/NIDAQmx_task_wrapper_methods.h
OUTFILE_NI_CPP=${OUTPUT_DIR}/NIDAQmx_ni_wrapper_methods.cpp
OUTFILE_NI_H=${OUTPUT_DIR}/NIDAQmx_ni_wrapper_methods.h

grep 'int32 __CFUNC.*(TaskHandle task\(Handle\)\?.*);' ${NIDAQmx_file} | perl -pe 's/;.*$/ {return 0;}/' > ${OUTPUT_DIR}/NIDAQmx_task_dummy.cpp
grep 'int32 __CFUNC .*(TaskHandle task\(Handle\)\?.*);' ${NIDAQmx_file} > ${OUTFILE_TASK_H}
perl -pe 's/;.*$/ {}/' $OUTFILE_TASK_H > $OUTFILE_TASK_CPP
spatch --in-place --c++ wrapper_task.cocci "$OUTFILE_TASK_CPP" > /dev/null || exit 1

perl -i -pe 's/int32 (activeEdge)/NITask::Edge \1/' $OUTFILE_TASK_CPP
perl -i -pe 's/int32 (sampleMode)/NITask::SampleMode \1/' $OUTFILE_TASK_CPP
perl -i -pe 's/int32 (lineGrouping)/NITask::LineGrouping \1/' $OUTFILE_TASK_CPP
perl -i -pe 's/bool32 (dataLayout)/NITask::DataLayout \1/' $OUTFILE_TASK_CPP
perl -i -pe 's/int32 (terminalConfig)/NITask::TerminalConfig \1/' $OUTFILE_TASK_CPP
perl -i -pe 's/int32 (idleState)/NITask::IdleState \1/' $OUTFILE_TASK_CPP

perl -0777 -pe 's/ \{.*?\}/;/gs' $OUTFILE_TASK_CPP > $OUTFILE_TASK_H
perl -i -pe 's/__NITask__ //' $OUTFILE_TASK_H
perl -i -pe 's/__NITask__ /NITask::/' $OUTFILE_TASK_CPP
sed -i '1i//THIS FILE IS AUTOGENERATED -- DO NOT EDIT' $OUTFILE_TASK_CPP
